pub mod api_config {
    // Generated by [`prost-build`]
    include!(concat!(env!("OUT_DIR"), "/api_config.rs"));
    // Generated by [`pbjson-build`]
    include!(concat!(env!("OUT_DIR"), "/api_config.serde.rs"));
}

fn main() {
    let mut config = api_config::ApiConfig::default();
    config.telegram_api_code = "world".into();

    println!("{:#?}", config);
}
